# All written by Lucas Bertoni

version: '3.4'

volumes:
  data:

services:



  client:
    image: client
    build:
      context: client/react-typescript-app
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    links:
      - authentication
    networks:
      - apinet



  authentication:
    image: authentication
    build:
      context: server/authentication
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      PROD_POSTGRES_STRING: $PROD_POSTGRES_STRING
    ports:
      - 4001:4001
    restart: on-failure
    depends_on:
      - authentication_database
    networks:
      - apinet



  eventbus:
    image: eventbus
    build:
      context: server/event-bus
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4002:4002
    restart: on-failure
    networks:
      - apinet



  eventlogger:
    image: eventlogger
    build:
      context: server/event-logger
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      PROD_POSTGRES_STRING: $PROD_POSTGRES_STRING
    ports:
      - 4003:4003
    restart: on-failure
    depends_on:
      - eventlogs_database
    networks:
      - apinet



  share:
    image: share
    build:
      context: server/share
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4004:4004
    restart: on-failure
    depends_on:
      - share_database
    networks:
      - apinet



  authentication_database:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
      - PGUSER=postgres
    ports:
      - 5000:5000
    volumes:
      - data:/var/lib/postgresql
    restart: always
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready" ]
        interval: 15s
        timeout: 10s
        retries: 5
    networks:
      - apinet



  eventlogs_database:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
      - PGUSER=postgres
    ports:
      - 5001:5001
    volumes:
      - data:/var/lib/postgresql
    restart: always
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready" ]
        interval: 15s
        timeout: 10s
        retries: 5
    networks:
      - apinet



  share_database:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
      - PGUSER=postgres
    ports:
      - 5002:5002
    volumes:
      - data:/var/lib/postgresql
    restart: always
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready" ]
        interval: 15s
        timeout: 10s
        retries: 5
    networks:
      - apinet



networks:
  apinet:
    driver: bridge